Fix tests not being run, Fix tests
Google Truth throws a NoSuchMethodError on Preconditions checkArgument
with a String as first argument, even though the code has a boolean at
that line, so that's weird, but this also means we Hamcrest nau